import { classifyIntent } from "../agents/classifier";
import { generateCoachReply } from "../agents/coach";
import { generatePlan } from "../agents/planner";
import { generateIdeasMenu } from "../agents/ideator";
import { generateDrafts } from "../agents/writer";
import { critiqueDrafts } from "../agents/critic";
import { extractStyleRules } from "../agents/styleExtractor";
import { extractCoreFacts } from "../agents/factExtractor";
import {
  extractAntiPattern,
  looksLikeMechanicalEdit,
  looksLikeNegativeFeedback,
} from "../agents/antiPatternExtractor";
import {
  createConversationMemorySnapshot,
  getConversationMemory,
  createConversationMemory,
  updateConversationMemory,
} from "../memory/memoryStore";
import { buildEffectiveContext, retrieveRelevantContext } from "../memory/contextRetriever";
import {
  buildRollingSummary,
  shouldRefreshRollingSummary,
} from "../memory/summaryManager";
import { retrieveAnchors } from "../core/retrieval";
import { generateStyleProfile, saveStyleProfile } from "../core/styleProfile";
import { checkDeterministicNovelty } from "../core/noveltyGate";
import { getXCharacterLimitForAccount } from "../../onboarding/draftArtifacts";
import { prisma } from "../../db";
import { buildClarificationTree } from "./clarificationTree";
import {
  buildSemanticRepairDirective,
  buildSemanticRepairState,
  inferCorrectionRepairQuestion,
} from "./correctionRepair";
import { buildDraftReply } from "./draftReply";
import { interpretPlannerFeedback } from "./plannerFeedback";
import type {
  CreatorChatQuickReply,
  DraftPreference,
  StrategyPlan,
  V2ChatIntent,
  V2ChatOutputShape,
  V2ConversationMemory,
} from "../contracts/chat";

export interface OrchestratorInput {
  userId: string;
  xHandle?: string | null;
  runId?: string;
  threadId?: string;
  userMessage: string;
  recentHistory: string;
  explicitIntent?: V2ChatIntent | null;
  activeDraft?: string;
}

export interface OrchestratorData {
  angles?: unknown[];
  plan?: StrategyPlan | null;
  draft?: string | null;
  supportAsset?: string | null;
  issuesFixed?: string[];
  quickReplies?: CreatorChatQuickReply[];
}

export type OrchestratorResponse = {
  mode: "coach" | "ideate" | "plan" | "draft" | "error";
  outputShape: V2ChatOutputShape;
  response: string;
  data?: OrchestratorData;
  memory: V2ConversationMemory;
};

function isLazyDraftRequest(message: string): boolean {
  const normalized = message.trim().toLowerCase();
  return [
    "just write anything",
    "write anything",
    "idk just write it",
    "just write it",
    "whatever works",
    "anything is fine",
  ].some((candidate) => normalized.includes(candidate));
}

function inferComparisonReference(message: string): string | null {
  const rebuildMatch = message.match(
    /\brebuild(?:ing)?\s+([a-z0-9][a-z0-9\s'-]{1,30}?)(?:\s+but\s+for|\s+for)\b/i,
  );
  if (rebuildMatch?.[1]) {
    return rebuildMatch[1].trim().replace(/[.,!?]+$/, "");
  }

  const likeMatch = message.match(
    /\blike\s+([a-z0-9][a-z0-9\s'-]{1,30}?)(?:\s+but\s+for|\s+for)\b/i,
  );
  if (likeMatch?.[1]) {
    return likeMatch[1].trim().replace(/[.,!?]+$/, "");
  }

  return null;
}

function hasFunctionalDetail(normalized: string): boolean {
  return [
    "it helps",
    "it does",
    "it lets",
    "it converts",
    "it turns",
    "it rewrites",
    "it automates",
    "it syncs",
    "it takes",
    "it pulls",
    "that helps",
    "that converts",
    "that turns",
    "to help",
    "to convert",
    "to turn",
    "to rewrite",
    "works for",
    "works with",
    "because",
  ].some((cue) => normalized.includes(cue));
}

function hasProblemDetail(normalized: string): boolean {
  return [
    "because",
    "so that",
    "so you can",
    "which means",
    "the problem",
    "the issue",
    "pain",
    "friction",
    "slow",
    "clunky",
    "manual",
    "doesn't",
    "doesnt",
    "hard",
    "different writing styles",
    "different styles",
    "different culture",
    "doesn't work",
    "doesnt work",
    "falls flat",
    "too long",
    "too polished",
  ].some((cue) => normalized.includes(cue));
}

function hasRelationshipDetail(normalized: string): boolean {
  return [
    "extension",
    "plugin",
    "works for",
    "works with",
    "alongside",
    "on top of",
    "inside",
    "after stanley",
    "after it writes",
    "after it generates",
    "generated by",
    "created by",
    "takes the",
    "uses the",
    "from stanley",
    "for stanley",
  ].some((cue) => normalized.includes(cue));
}

function inferMissingSpecificQuestion(message: string): string | null {
  const normalized = message.trim().toLowerCase();
  const comparisonReference = inferComparisonReference(message);

  const comparisonOnly =
    Boolean(comparisonReference) ||
    /\bbut for (x|twitter|linkedin)\b/.test(normalized) ||
    (normalized.includes("like stanley") &&
      ["app", "tool", "product", "extension", "plugin"].some((cue) =>
        normalized.includes(cue),
      ));

  const isBuildingSomething =
    ["building", "making", "working on", "creating", "shipping"].some((cue) =>
      normalized.includes(cue),
    ) &&
    ["extension", "plugin", "tool", "app", "product"].some((cue) =>
      normalized.includes(cue),
    ) ||
    comparisonOnly;

  if (!isBuildingSomething) {
    return null;
  }

  if (hasFunctionalDetail(normalized)) {
    if (comparisonOnly && !hasRelationshipDetail(normalized)) {
      const reference = comparisonReference || "the original tool";
      return `one more thing: how does it relate to ${reference} exactly - replacement, extension, or something that works alongside it?`;
    }

    if (!hasProblemDetail(normalized)) {
      return "nice. what's the actual problem it fixes, or why does it matter enough to post about?";
    }

    return null;
  }

  const targetMatch = message.match(/\bfor\s+([a-z0-9][a-z0-9\s'-]{1,30})/i);
  const rawTarget = targetMatch?.[1]?.trim().replace(/[.,!?]+$/, "") || "";

  if (comparisonOnly) {
    if (rawTarget) {
      return `quick check: what does your version actually do on ${rawTarget}, and what's different about it?`;
    }
    return "quick check: what does your version actually do, and what's different about it?";
  }

  if (normalized.includes("extension") || normalized.includes("plugin")) {
    if (rawTarget) {
      return `quick check: what does the extension do, and what should someone know about ${rawTarget}?`;
    }
    return "quick check: what does the extension actually do?";
  }

  if (rawTarget) {
    return `quick check: what does it do, and what should someone know about ${rawTarget}?`;
  }

  return "quick check: what does it actually do?";
}

function inferAbstractTopicSeed(
  message: string,
  memory: Pick<V2ConversationMemory, "conversationState" | "concreteAnswerCount" | "topicSummary">,
): string | null {
  if (memory.conversationState !== "needs_more_context" || memory.concreteAnswerCount >= 2) {
    return null;
  }

  const trimmed = message.trim();
  const normalized = trimmed.toLowerCase();
  if (!trimmed || normalized.startsWith(">")) {
    return null;
  }

  const containsSpecificCue =
    hasFunctionalDetail(normalized) ||
    hasProblemDetail(normalized) ||
    [
      "my take",
      "my opinion",
      "i think",
      "i learned",
      "i realized",
      "the point is",
      "the actual point",
      "because",
      "story",
      "mistake",
      "lesson",
      "hot take",
      "contrarian",
      "vs ",
      "versus",
      "why ",
      "how ",
    ].some((cue) => normalized.includes(cue));

  if (containsSpecificCue) {
    return null;
  }

  const isShortTopic =
    trimmed.length <= 48 &&
    trimmed.split(/\s+/).length <= 5 &&
    /^[a-z0-9\s/&'’-]+$/i.test(trimmed);

  if (!isShortTopic) {
    return null;
  }

  return trimmed.replace(/[.?!,]+$/, "") || memory.topicSummary || "this";
}

function inferBroadTopicDraftRequest(message: string): string | null {
  const normalized = message.trim().toLowerCase();
  const isDraftRequest = [
    "write me a post",
    "write a post",
    "draft a post",
    "draft me a post",
    "make a post",
    "make me a post",
    "give me a post",
  ].some((cue) => normalized.includes(cue));

  if (!isDraftRequest) {
    return null;
  }

  const hasDirectionCue = [
    "in my voice",
    "my voice",
    "random",
    "whatever",
    "optimized for growth",
    "optimize it for growth",
    "optimize for growth",
    "for reach",
    "for engagement",
    "to grow",
    "viral",
    "hook",
    "hot take",
    "story",
    "lesson",
    "mistake",
    "opinion",
    "personal",
    "thread",
    "announcement",
    "launch",
    "tips",
    "how to",
    "why ",
    "vs ",
    "versus",
    "counter-",
    "contrarian",
  ].some((cue) => normalized.includes(cue));

  if (hasDirectionCue) {
    return null;
  }

  const topicMatch = message.match(/\b(?:about|on)\s+([a-z0-9][a-z0-9\s/&'’-]{1,80})$/i);
  const topic = topicMatch?.[1]?.trim().replace(/[.?!,]+$/, "").replace(/\s+/g, " ") || "";

  if (!topic) {
    return null;
  }

  const normalizedTopic = topic.toLowerCase();
  if (
    ["it", "this", "that", "something", "anything", "stuff"].includes(normalizedTopic) ||
    topic.split(/\s+/).length > 5
  ) {
    return null;
  }

  if (
    [
      "why ",
      "how ",
      "when ",
      "mistake",
      "lesson",
      "story",
      "hot take",
      "opinion",
      "tips",
      "launch",
      "announcement",
      "review",
      "breakdown",
    ].some((cue) => normalizedTopic.includes(cue))
  ) {
    return null;
  }

  return topic;
}

function inferDraftPreference(
  message: string,
  fallback: DraftPreference = "balanced",
): DraftPreference {
  const normalized = message.trim().toLowerCase();

  const voiceFirst = [
    "in my voice",
    "my voice",
    "sound like me",
    "sounds like me",
    "keep it natural",
    "natural, not growth-hacky",
    "not growth-hacky",
    "not growth hacky",
    "not too growthy",
    "less growthy",
    "less optimized",
    "more natural",
    "more casual",
    "more like me",
  ].some((cue) => normalized.includes(cue));

  if (voiceFirst) {
    return "voice_first";
  }

  const growthFirst = [
    "optimized for growth",
    "optimize it for growth",
    "optimize for growth",
    "for growth and reach",
    "for growth",
    "for reach",
    "for engagement",
    "for impressions",
    "more viral",
    "make it punchier",
    "stronger hook",
    "growth-focused",
  ].some((cue) => normalized.includes(cue));

  if (growthFirst) {
    return "growth_first";
  }

  return fallback;
}

function withDraftPreference(
  plan: StrategyPlan,
  draftPreference: DraftPreference,
): StrategyPlan {
  if (draftPreference === "balanced") {
    const nextPlan = { ...plan };
    delete nextPlan.deliveryPreference;
    return nextPlan;
  }

  return {
    ...plan,
    deliveryPreference: draftPreference,
  };
}

function buildPlanPitch(plan: StrategyPlan): string {
  const laneLabel =
    plan.targetLane === "reply"
      ? "a reply"
      : plan.targetLane === "quote"
        ? "a quote post"
        : "an original post";
  const hookLabel = plan.hookType.trim().toLowerCase() || "clear";

  return `i'm thinking we make this ${laneLabel} with a ${hookLabel} angle. want me to draft it?`;
}

function buildPlanQuickReplies(): CreatorChatQuickReply[] {
  return [
    {
      kind: "planner_action",
      value: "looks good, write it",
      label: "Looks good",
      explicitIntent: "planner_feedback",
    },
    {
      kind: "planner_action",
      value: "make it tighter and more blunt",
      label: "Tighten it",
      explicitIntent: "planner_feedback",
    },
    {
      kind: "planner_action",
      value: "different angle",
      label: "Different angle",
      explicitIntent: "planner_feedback",
    },
  ];
}

function applyMemoryPatch(
  current: V2ConversationMemory,
  patch: Partial<V2ConversationMemory>,
): V2ConversationMemory {
  return {
    ...current,
    ...patch,
    activeConstraints: patch.activeConstraints ?? current.activeConstraints,
    pendingPlan:
      patch.pendingPlan === undefined ? current.pendingPlan : patch.pendingPlan,
    clarificationState:
      patch.clarificationState === undefined
        ? current.clarificationState
        : patch.clarificationState,
    rollingSummary:
      patch.rollingSummary === undefined ? current.rollingSummary : patch.rollingSummary,
  };
}

async function maybeCaptureAntiPattern(args: {
  userId: string;
  userMessage: string;
  activeDraft?: string;
  recentHistory: string;
  styleCard: Awaited<ReturnType<typeof generateStyleProfile>>;
  xHandle: string;
}): Promise<string[]> {
  if (
    args.userId === "anonymous" ||
    !args.styleCard ||
    !args.activeDraft ||
    !looksLikeNegativeFeedback(args.userMessage) ||
    looksLikeMechanicalEdit(args.userMessage)
  ) {
    return args.styleCard?.customGuidelines?.slice(-2) || [];
  }

  const extracted = await extractAntiPattern(
    args.userMessage,
    args.activeDraft,
    args.recentHistory,
  );

  if (!extracted?.shouldCapture || extracted.patternTags.length === 0) {
    return args.styleCard.customGuidelines.slice(-2);
  }

  const nextGuidelines = Array.from(
    new Set([
      ...(args.styleCard.customGuidelines || []),
      ...extracted.patternTags.map((tag) => `Avoid ${tag}`),
    ]),
  );

  args.styleCard.customGuidelines = nextGuidelines;
  saveStyleProfile(args.userId, args.xHandle, args.styleCard).catch((error) =>
    console.error("Failed to save anti-pattern guidance:", error),
  );

  return nextGuidelines.slice(-2);
}

/**
 * The V2 state machine.
 */
export async function manageConversationTurn(
  input: OrchestratorInput,
): Promise<OrchestratorResponse> {
  const {
    userId,
    xHandle,
    runId,
    threadId,
    userMessage,
    recentHistory,
    explicitIntent,
    activeDraft,
  } = input;
  const effectiveXHandle = xHandle || "default";

  let memoryRecord = await getConversationMemory({ runId, threadId });
  if (!memoryRecord) {
    memoryRecord = await createConversationMemory({
      runId,
      threadId,
      userId: userId === "anonymous" ? null : userId,
    });
  }

  let memory = createConversationMemorySnapshot(
    memoryRecord as unknown as Record<string, unknown>,
  );

  let classification;
  if (!explicitIntent) {
    classification = await classifyIntent(userMessage, recentHistory);
    if (!classification) {
      return {
        mode: "error",
        outputShape: "coach_question",
        response: "Failed to classify intent.",
        memory,
      };
    }
  } else {
    classification = {
      intent: explicitIntent,
      needs_memory_update: false,
      confidence: 1,
    };
  }

  if (classification.needs_memory_update) {
    const nextConstraints = Array.from(
      new Set([...memory.activeConstraints, userMessage]),
    );
    const updated = await updateConversationMemory({
      runId,
      threadId,
      activeConstraints: nextConstraints,
    });
    memory = createConversationMemorySnapshot(updated as unknown as Record<string, unknown>);
  }

  let mode = classification.intent;

  if (
    !explicitIntent &&
    ["hello", "hi", "help me grow", "i want to grow"].includes(
      userMessage.toLowerCase().trim(),
    )
  ) {
    mode = "coach";
  }

  if (!explicitIntent && mode === "draft" && !activeDraft) {
    mode = "plan";
  }

  const [styleCard, anchors, extractedRules, extractedFacts] = await Promise.all([
    generateStyleProfile(userId, effectiveXHandle, 20),
    retrieveAnchors(userId, effectiveXHandle, userMessage || memory.topicSummary || "growth"),
    userId !== "anonymous" ? extractStyleRules(userMessage, recentHistory) : Promise.resolve(null),
    userId !== "anonymous" ? extractCoreFacts(userMessage, recentHistory) : Promise.resolve(null),
  ]);

  if (styleCard && extractedRules && extractedRules.length > 0) {
    styleCard.customGuidelines = Array.from(
      new Set([...(styleCard.customGuidelines || []), ...extractedRules]),
    );
    saveStyleProfile(userId, effectiveXHandle, styleCard).catch((error) =>
      console.error("Failed to save style profile:", error),
    );
  }

  if (styleCard && extractedFacts && extractedFacts.length > 0) {
    styleCard.contextAnchors = Array.from(
      new Set([...(styleCard.contextAnchors || []), ...extractedFacts]),
    );
    saveStyleProfile(userId, effectiveXHandle, styleCard).catch((error) =>
      console.error("Failed to save style profile:", error),
    );
  }

  const antiPatterns = await maybeCaptureAntiPattern({
    userId,
    userMessage,
    activeDraft,
    recentHistory,
    styleCard,
    xHandle: effectiveXHandle,
  });

  const relevantTopicAnchors = retrieveRelevantContext({
    userMessage,
    topicSummary: memory.topicSummary,
    rollingSummary: memory.rollingSummary,
    topicAnchors: anchors.topicAnchors,
  });

  const effectiveContext = buildEffectiveContext({
    recentHistory,
    rollingSummary: memory.rollingSummary,
    relevantTopicAnchors,
  });

  const storedRun = await prisma.onboardingRun.findUnique({ where: { id: runId } });
  const onboardingResult = storedRun?.result as Record<string, unknown> | undefined;
  const onboardingProfile = onboardingResult?.profile as Record<string, unknown> | undefined;
  const maxCharacterLimit = getXCharacterLimitForAccount(
    onboardingProfile?.isVerified === true,
  );
  const stage = typeof onboardingResult?.growthStage === "string"
    ? onboardingResult.growthStage
    : "Unknown";
  const strategyState = onboardingResult?.strategyState as Record<string, unknown> | undefined;
  const goal = typeof strategyState?.goal === "string" ? strategyState.goal : "Audience growth";
  const contextAnchorsStr =
    styleCard && styleCard.contextAnchors?.length > 0
      ? `\n- Known Facts: ${styleCard.contextAnchors.join(" | ")}`
      : "";

  const userContextString = `
User Profile Summary:
- Stage: ${stage}
- Primary Goal: ${goal}${contextAnchorsStr}
  `.trim();

  const writeMemory = async (
    patch: Partial<V2ConversationMemory> & {
      topicSummary?: string | null;
      concreteAnswerCount?: number;
      currentDraftArtifactId?: string | null;
    },
  ) => {
    const optimistic = applyMemoryPatch(memory, {
      conversationState: patch.conversationState,
      activeConstraints: patch.activeConstraints,
      pendingPlan: patch.pendingPlan,
      clarificationState: patch.clarificationState,
      rollingSummary: patch.rollingSummary,
      assistantTurnCount: patch.assistantTurnCount,
      topicSummary: patch.topicSummary ?? memory.topicSummary,
      concreteAnswerCount:
        patch.concreteAnswerCount ?? memory.concreteAnswerCount,
      currentDraftArtifactId:
        patch.currentDraftArtifactId ?? memory.currentDraftArtifactId,
    });

    const updated = await updateConversationMemory({
      runId,
      threadId,
      topicSummary: patch.topicSummary,
      activeConstraints: patch.activeConstraints,
      concreteAnswerCount: patch.concreteAnswerCount,
      lastDraftArtifactId: patch.currentDraftArtifactId,
      conversationState: patch.conversationState,
      pendingPlan: patch.pendingPlan,
      clarificationState: patch.clarificationState,
      rollingSummary: patch.rollingSummary,
      assistantTurnCount: patch.assistantTurnCount,
    });

    memory = updated
      ? createConversationMemorySnapshot(updated as unknown as Record<string, unknown>)
      : optimistic;
  };

  const nextAssistantTurnCount = memory.assistantTurnCount + 1;
  const turnDraftPreference = inferDraftPreference(
    userMessage,
    memory.pendingPlan?.deliveryPreference || "balanced",
  );
  let draftInstruction = userMessage;

  if (
    !explicitIntent &&
    activeDraft &&
    memory.clarificationState?.branchKey === "semantic_repair"
  ) {
    const repairDirective = buildSemanticRepairDirective(
      userMessage,
      memory.topicSummary,
    );
    const nextConstraints = Array.from(
      new Set([...memory.activeConstraints, repairDirective.constraint]),
    );

    await writeMemory({
      activeConstraints: nextConstraints,
      clarificationState: null,
      conversationState: "editing",
    });

    mode = "edit";
    draftInstruction = repairDirective.rewriteRequest;
  }

  if (
    mode === "planner_feedback" &&
    memory.conversationState === "plan_pending_approval" &&
    memory.pendingPlan
  ) {
    const decision = await interpretPlannerFeedback(userMessage, memory.pendingPlan);

    if (decision === "approve") {
      const approvedPlan = memory.pendingPlan;
      const pastPosts = await prisma.post.findMany({
        where: { userId },
        orderBy: { createdAt: "desc" },
        take: 100,
        select: { text: true },
      });
      const historicalTexts = pastPosts.map((post) => post.text);

      const writerOutput = await generateDrafts(
        approvedPlan,
        styleCard,
        relevantTopicAnchors,
        memory.activeConstraints,
        effectiveContext,
        activeDraft,
        {
          conversationState: memory.conversationState,
          antiPatterns,
          maxCharacterLimit,
          goal,
          draftPreference: approvedPlan.deliveryPreference || turnDraftPreference,
        },
      );

      if (!writerOutput) {
        return {
          mode: "error",
          outputShape: "coach_question",
          response: "Failed to write draft.",
          memory,
        };
      }

      const criticOutput = await critiqueDrafts(
        writerOutput,
        memory.activeConstraints,
        styleCard,
        {
          maxCharacterLimit,
          draftPreference: approvedPlan.deliveryPreference || turnDraftPreference,
        },
      );

      if (!criticOutput) {
        return {
          mode: "error",
          outputShape: "coach_question",
          response: "Failed to critique draft.",
          memory,
        };
      }

      const noveltyCheck = checkDeterministicNovelty(
        criticOutput.finalDraft,
        historicalTexts,
      );
      if (!noveltyCheck.isNovel) {
        const clarification = buildClarificationTree({
          branchKey: "plan_reject",
          seedTopic: approvedPlan.objective,
          styleCard,
          topicAnchors: relevantTopicAnchors,
        });

        await writeMemory({
          conversationState: "needs_more_context",
          pendingPlan: null,
          clarificationState: clarification.clarificationState,
          assistantTurnCount: nextAssistantTurnCount,
        });

        return {
          mode: "coach",
          outputShape: "coach_question",
          response:
            "this version felt too close to something you've already posted. let's shift it.",
          data: { quickReplies: clarification.quickReplies },
          memory,
        };
      }

      const rollingSummary = buildRollingSummary({
        currentSummary: memory.rollingSummary,
        topicSummary: approvedPlan.objective,
        approvedPlan,
        activeConstraints: memory.activeConstraints,
        latestDraftStatus: "Draft delivered",
      });

      await writeMemory({
        topicSummary: approvedPlan.objective,
        conversationState: "draft_ready",
        pendingPlan: null,
        clarificationState: null,
        rollingSummary,
        assistantTurnCount: nextAssistantTurnCount,
      });

      return {
        mode: "draft",
        outputShape: "short_form_post",
        response: buildDraftReply({
          userMessage,
          draftPreference: approvedPlan.deliveryPreference || turnDraftPreference,
          isEdit: Boolean(activeDraft),
          issuesFixed: criticOutput.issues,
        }),
        data: {
          draft: criticOutput.finalDraft,
          supportAsset: writerOutput.supportAsset,
          issuesFixed: criticOutput.issues,
        },
        memory,
      };
    }

    if (decision === "revise") {
      const revisionPrompt = [
        `Current plan objective: ${memory.pendingPlan.objective}`,
        `Current plan angle: ${memory.pendingPlan.angle}`,
        `Requested revision: ${userMessage}`,
      ].join("\n");

      const revisedPlan = await generatePlan(
        revisionPrompt,
        memory.topicSummary,
        memory.activeConstraints,
        effectiveContext,
        activeDraft,
        {
          goal,
          conversationState: memory.conversationState,
          antiPatterns,
          draftPreference: turnDraftPreference,
        },
      );

      if (!revisedPlan) {
        return {
          mode: "error",
          outputShape: "coach_question",
          response: "Failed to revise the plan.",
          memory,
        };
      }

      const revisedPlanWithPreference = withDraftPreference(
        revisedPlan,
        turnDraftPreference,
      );

      await writeMemory({
        topicSummary: revisedPlanWithPreference.objective,
        conversationState: "plan_pending_approval",
        pendingPlan: revisedPlanWithPreference,
        clarificationState: null,
        assistantTurnCount: nextAssistantTurnCount,
      });

      return {
        mode: "plan",
        outputShape: "planning_outline",
        response: buildPlanPitch(revisedPlanWithPreference),
        data: {
          plan: revisedPlanWithPreference,
          quickReplies: buildPlanQuickReplies(),
        },
        memory,
      };
    }

    if (decision === "reject") {
      const clarification = buildClarificationTree({
        branchKey: "plan_reject",
        seedTopic: memory.pendingPlan.objective,
        styleCard,
        topicAnchors: relevantTopicAnchors,
      });

      await writeMemory({
        conversationState: "needs_more_context",
        pendingPlan: null,
        clarificationState: clarification.clarificationState,
        assistantTurnCount: nextAssistantTurnCount,
      });

      return {
        mode: "coach",
        outputShape: "coach_question",
        response: clarification.reply,
        data: {
          quickReplies: clarification.quickReplies,
        },
        memory,
      };
    }

    await writeMemory({
      conversationState: "plan_pending_approval",
      pendingPlan: memory.pendingPlan,
      assistantTurnCount: nextAssistantTurnCount,
    });

    return {
      mode: "plan",
      outputShape: "planning_outline",
      response: "say the word and i'll draft it, or tell me what to tweak.",
      data: {
        plan: memory.pendingPlan,
        quickReplies: buildPlanQuickReplies(),
      },
      memory,
    };
  }

  if (
    !explicitIntent &&
    mode === "plan"
  ) {
    const clarificationQuestion = inferMissingSpecificQuestion(userMessage);

    if (clarificationQuestion) {
      await writeMemory({
        conversationState: "needs_more_context",
        clarificationState: null,
        assistantTurnCount: nextAssistantTurnCount,
      });

      return {
        mode: "coach",
        outputShape: "coach_question",
        response: clarificationQuestion,
        memory,
      };
    }
  }

  if (!explicitIntent && mode === "plan") {
    const broadTopic = inferBroadTopicDraftRequest(userMessage);

    if (broadTopic) {
      const clarification = buildClarificationTree({
        branchKey: "topic_known_but_direction_missing",
        seedTopic: broadTopic,
        styleCard,
        topicAnchors: relevantTopicAnchors,
      });

      await writeMemory({
        topicSummary: broadTopic,
        conversationState: "needs_more_context",
        clarificationState: clarification.clarificationState,
        assistantTurnCount: nextAssistantTurnCount,
      });

      return {
        mode: "coach",
        outputShape: "coach_question",
        response: clarification.reply,
        data: {
          quickReplies: clarification.quickReplies,
        },
        memory,
      };
    }
  }

  if (
    !explicitIntent &&
    mode === "plan" &&
    !memory.topicSummary &&
    memory.concreteAnswerCount < 2 &&
    classification.confidence < 0.7
  ) {
    const branchKey = isLazyDraftRequest(userMessage)
      ? "lazy_request"
      : "vague_draft_request";
    const clarification = buildClarificationTree({
      branchKey,
      seedTopic: userMessage || memory.topicSummary,
      styleCard,
      topicAnchors: relevantTopicAnchors,
    });

    await writeMemory({
      conversationState: "needs_more_context",
      clarificationState: clarification.clarificationState,
      assistantTurnCount: nextAssistantTurnCount,
    });

    return {
      mode: "coach",
      outputShape: "coach_question",
      response: clarification.reply,
      data: {
        quickReplies: clarification.quickReplies,
      },
      memory,
    };
  }

  if (!explicitIntent && mode === "plan") {
    const abstractTopicSeed = inferAbstractTopicSeed(userMessage, memory);

    if (abstractTopicSeed) {
      const clarification = buildClarificationTree({
        branchKey: "abstract_topic_focus_pick",
        seedTopic: abstractTopicSeed,
        styleCard,
        topicAnchors: relevantTopicAnchors,
      });

      await writeMemory({
        topicSummary: abstractTopicSeed,
        conversationState: "needs_more_context",
        clarificationState: clarification.clarificationState,
        assistantTurnCount: nextAssistantTurnCount,
      });

      return {
        mode: "coach",
        outputShape: "coach_question",
        response: clarification.reply,
        data: {
          quickReplies: clarification.quickReplies,
        },
        memory,
      };
    }
  }

  if (!explicitIntent && activeDraft) {
    const correctionRepairQuestion = inferCorrectionRepairQuestion(
      userMessage,
      memory.topicSummary,
    );

    if (correctionRepairQuestion) {
      await writeMemory({
        conversationState: "needs_more_context",
        clarificationState: buildSemanticRepairState(memory.topicSummary),
        assistantTurnCount: nextAssistantTurnCount,
      });

      return {
        mode: "coach",
        outputShape: "coach_question",
        response: correctionRepairQuestion,
        memory,
      };
    }
  }

  switch (mode) {
    case "ideate": {
      const ideas = await generateIdeasMenu(
        userMessage,
        memory.topicSummary,
        effectiveContext,
        styleCard,
        relevantTopicAnchors,
        userContextString,
        {
          goal,
          conversationState: memory.conversationState,
          antiPatterns,
        },
      );

      await writeMemory({
        topicSummary: userMessage,
        conversationState: "ready_to_ideate",
        clarificationState: null,
        assistantTurnCount: nextAssistantTurnCount,
        rollingSummary: shouldRefreshRollingSummary(nextAssistantTurnCount, false)
          ? buildRollingSummary({
              currentSummary: memory.rollingSummary,
              topicSummary: userMessage,
              approvedPlan: null,
              activeConstraints: memory.activeConstraints,
              latestDraftStatus: "Ideation in progress",
              unresolvedQuestion: ideas?.close || null,
            })
          : memory.rollingSummary,
      });

      return {
        mode: "ideate",
        outputShape: "ideation_angles",
        response: ideas?.close || "here are a few angles — which one feels right?",
        data: ideas ? { angles: ideas.angles } : undefined,
        memory,
      };
    }

    case "plan": {
      const plan = await generatePlan(
        userMessage,
        memory.topicSummary,
        memory.activeConstraints,
        effectiveContext,
        activeDraft,
        {
          goal,
          conversationState: memory.conversationState,
          antiPatterns,
          draftPreference: turnDraftPreference,
        },
      );

      if (!plan) {
        return {
          mode: "error",
          outputShape: "coach_question",
          response: "Failed to generate strategy plan.",
          memory,
        };
      }

      const planWithPreference = withDraftPreference(plan, turnDraftPreference);

      await writeMemory({
        topicSummary: planWithPreference.objective,
        conversationState: "plan_pending_approval",
        pendingPlan: planWithPreference,
        clarificationState: null,
        assistantTurnCount: nextAssistantTurnCount,
      });

      return {
        mode: "plan",
        outputShape: "planning_outline",
        response: buildPlanPitch(planWithPreference),
        data: {
          plan: planWithPreference,
          quickReplies: buildPlanQuickReplies(),
        },
        memory,
      };
    }

    case "draft":
    case "review":
    case "edit": {
      const pastPosts = await prisma.post.findMany({
        where: { userId },
        orderBy: { createdAt: "desc" },
        take: 100,
        select: { text: true },
      });
      const historicalTexts = pastPosts.map((post) => post.text);

      const plan = await generatePlan(
        draftInstruction,
        memory.topicSummary,
        memory.activeConstraints,
        effectiveContext,
        activeDraft,
        {
          goal,
          conversationState: memory.conversationState,
          antiPatterns,
          draftPreference: turnDraftPreference,
        },
      );

      if (!plan) {
        return {
          mode: "error",
          outputShape: "coach_question",
          response: "Failed to generate strategy plan.",
          memory,
        };
      }

      const planWithPreference = withDraftPreference(plan, turnDraftPreference);

      const writerOutput = await generateDrafts(
        planWithPreference,
        styleCard,
        relevantTopicAnchors,
        memory.activeConstraints,
        effectiveContext,
        activeDraft,
        {
          conversationState: memory.conversationState,
          antiPatterns,
          maxCharacterLimit,
          goal,
          draftPreference: planWithPreference.deliveryPreference || turnDraftPreference,
        },
      );

      if (!writerOutput) {
        return {
          mode: "error",
          outputShape: "coach_question",
          response: "Failed to write draft.",
          memory,
        };
      }

      const criticOutput = await critiqueDrafts(
        writerOutput,
        memory.activeConstraints,
        styleCard,
        {
          maxCharacterLimit,
          draftPreference: planWithPreference.deliveryPreference || turnDraftPreference,
        },
      );

      if (!criticOutput) {
        return {
          mode: "error",
          outputShape: "coach_question",
          response: "Failed to critique draft.",
          memory,
        };
      }

      const noveltyCheck = checkDeterministicNovelty(
        criticOutput.finalDraft,
        historicalTexts,
      );
      if (!noveltyCheck.isNovel) {
        const clarification = buildClarificationTree({
          branchKey: "plan_reject",
          seedTopic: plan.objective,
          styleCard,
          topicAnchors: relevantTopicAnchors,
        });

        await writeMemory({
          conversationState: "needs_more_context",
          pendingPlan: null,
          clarificationState: clarification.clarificationState,
          assistantTurnCount: nextAssistantTurnCount,
        });

        return {
          mode: "coach",
          outputShape: "coach_question",
          response: "that version felt too close to something you've already posted. let's shift it.",
          data: {
            quickReplies: clarification.quickReplies,
          },
          memory,
        };
      }

      const rollingSummary = shouldRefreshRollingSummary(nextAssistantTurnCount, false)
        ? buildRollingSummary({
            currentSummary: memory.rollingSummary,
            topicSummary: planWithPreference.objective,
            approvedPlan: planWithPreference,
            activeConstraints: memory.activeConstraints,
            latestDraftStatus: "Draft delivered",
          })
        : memory.rollingSummary;

      await writeMemory({
        topicSummary: planWithPreference.objective,
        conversationState: "draft_ready",
        pendingPlan: null,
        clarificationState: null,
        rollingSummary,
        assistantTurnCount: nextAssistantTurnCount,
      });

      return {
        mode: "draft",
        outputShape: "short_form_post",
        response: buildDraftReply({
          userMessage,
          draftPreference:
            planWithPreference.deliveryPreference || turnDraftPreference,
          isEdit: Boolean(activeDraft),
          issuesFixed: criticOutput.issues,
        }),
        data: {
          draft: criticOutput.finalDraft,
          supportAsset: writerOutput.supportAsset,
          issuesFixed: criticOutput.issues,
        },
        memory,
      };
    }

    case "coach":
    case "answer_question":
    default: {
      const coachReply = await generateCoachReply(
        userMessage,
        effectiveContext,
        memory.topicSummary,
        styleCard,
        relevantTopicAnchors,
        userContextString,
        {
          goal,
          conversationState: memory.conversationState,
          antiPatterns,
        },
      );

      const nextConcreteAnswerCount =
        userMessage.length > 15
          ? memory.concreteAnswerCount + 1
          : memory.concreteAnswerCount;

      const rollingSummary = shouldRefreshRollingSummary(nextAssistantTurnCount, false)
        ? buildRollingSummary({
            currentSummary: memory.rollingSummary,
            topicSummary: memory.topicSummary,
            approvedPlan: memory.pendingPlan,
            activeConstraints: memory.activeConstraints,
            latestDraftStatus: "Context gathering",
            unresolvedQuestion: coachReply?.probingQuestion || null,
          })
        : memory.rollingSummary;

      await writeMemory({
        conversationState:
          memory.pendingPlan && memory.conversationState === "plan_pending_approval"
            ? "plan_pending_approval"
            : "needs_more_context",
        concreteAnswerCount: nextConcreteAnswerCount,
        rollingSummary,
        assistantTurnCount: nextAssistantTurnCount,
      });

      return {
        mode: "coach",
        outputShape: "coach_question",
        response:
          coachReply?.response ||
          "what's on your mind? i can help you draft, ideate, or figure out what to post.",
        memory,
      };
    }
  }
}
