export type DraftContextDomainHint = "product" | "career" | "creator" | "general";

export interface DraftContextSlots {
  subjectKnown: boolean;
  behaviorKnown: boolean;
  stakesKnown: boolean;
  externalContextKnown: boolean;
  entityNeedsDefinition: boolean;
  namedEntity: string | null;
  ambiguousReferenceNeedsClarification: boolean;
  ambiguousReference: string | null;
  isProductLike: boolean;
  domainHint: DraftContextDomainHint;
}

export function inferComparisonReference(message: string): string | null {
  const rebuildMatch = message.match(
    /\brebuild(?:ing)?\s+([a-z0-9][a-z0-9\s'-]{1,30}?)(?:\s+but\s+for|\s+for)\b/i,
  );
  if (rebuildMatch?.[1]) {
    return rebuildMatch[1].trim().replace(/[.,!?]+$/, "");
  }

  const likeMatch = message.match(
    /\blike\s+([a-z0-9][a-z0-9\s'-]{1,30}?)(?:\s+but\s+for|\s+for)\b/i,
  );
  if (likeMatch?.[1]) {
    return likeMatch[1].trim().replace(/[.,!?]+$/, "");
  }

  return null;
}

export function hasFunctionalDetail(normalized: string): boolean {
  return [
    "it helps",
    "it does",
    "it lets",
    "it converts",
    "it turns",
    "it rewrites",
    "it automates",
    "it syncs",
    "it takes",
    "it pulls",
    "that helps",
    "that converts",
    "that turns",
    "to help",
    "to convert",
    "to turn",
    "to rewrite",
    "works for",
    "works with",
    "because",
  ].some((cue) => normalized.includes(cue));
}

export function hasProblemDetail(normalized: string): boolean {
  return [
    "because",
    "so that",
    "so you can",
    "which means",
    "the problem",
    "the issue",
    "pain",
    "friction",
    "slow",
    "clunky",
    "manual",
    "doesn't",
    "doesnt",
    "hard",
    "different writing styles",
    "different styles",
    "different culture",
    "doesn't work",
    "doesnt work",
    "falls flat",
    "too long",
    "too polished",
  ].some((cue) => normalized.includes(cue));
}

export function hasRelationshipDetail(normalized: string): boolean {
  return [
    "extension",
    "plugin",
    "works for",
    "works with",
    "alongside",
    "on top of",
    "inside",
    "after stanley",
    "after it writes",
    "after it generates",
    "generated by",
    "created by",
    "takes the",
    "uses the",
    "from stanley",
    "for stanley",
  ].some((cue) => normalized.includes(cue));
}

function looksLikeBuildMessage(normalized: string): boolean {
  return (
    ["building", "making", "creating", "shipping", "rebuilding"].some((cue) =>
      normalized.includes(cue),
    ) &&
    ["tool", "app", "product", "extension", "plugin"].some((cue) =>
      normalized.includes(cue),
    )
  );
}

function inferBuildSubject(message: string): string | null {
  const match = message.match(
    /\b(?:building|making|creating|shipping|launching|working on|rebuilding)\s+([a-z0-9][a-z0-9\s'-]{1,30}?)(?:\s+for\b|\s+on\b|\s+with\b|[.?!,]|$)/i,
  );
  const candidate = match?.[1]?.trim().replace(/[.?!,]+$/, "") || "";
  if (!candidate) {
    return null;
  }

  const normalized = candidate.toLowerCase();
  if (
    [
      "something",
      "anything",
      "everything",
      "content",
      "posts",
      "post",
      "tool",
      "app",
      "product",
      "extension",
      "plugin",
    ].includes(normalized) ||
    normalized.startsWith("a ") ||
    normalized.startsWith("an ") ||
    normalized.startsWith("my ")
  ) {
    return null;
  }

  return candidate;
}

function inferNamedEntity(message: string): string | null {
  const cleanCandidate = (value: string | undefined): string | null => {
    const candidate = value?.trim().replace(/[.?!,]+$/, "") || "";
    if (!candidate) {
      return null;
    }

    const normalized = candidate.toLowerCase();
    const weakSeeds = new Set([
      "me",
      "myself",
      "my",
      "i",
      "it",
      "this",
      "that",
      "what",
      "something",
      "someone",
      "anything",
      "everything",
      "my thing",
    ]);

    if (
      weakSeeds.has(normalized) ||
      normalized.startsWith("my ") ||
      normalized.startsWith("me ") ||
      normalized.includes(" for ") ||
      normalized.includes(" with ") ||
      normalized.includes(" using ")
    ) {
      return null;
    }

    return candidate;
  };

  const productLinkedMatch = message.match(
    /\b(?:extension|plugin|tool|app|product)\s+(?:for|with|using)\s+([a-z0-9][a-z0-9\s'-]{1,30})/i,
  );
  const comparisonMatch = message.match(
    /\b(?:like|alongside)\s+([a-z0-9][a-z0-9\s'-]{1,30})/i,
  );
  const genericMatch = message.match(
    /\b(?:for|with|using)\s+([a-z0-9][a-z0-9\s'-]{1,30})/i,
  );

  return (
    cleanCandidate(inferBuildSubject(message) || undefined) ||
    cleanCandidate(productLinkedMatch?.[1]) ||
    cleanCandidate(comparisonMatch?.[1]) ||
    cleanCandidate(genericMatch?.[1])
  );
}

function hasCareerCue(normalized: string): boolean {
  return [
    "internship",
    "interview",
    "job hunt",
    "job search",
    "recruiter",
    "application",
    "offer",
    "resume",
    "career",
    "cold dm",
    "cold dms",
  ].some((cue) => normalized.includes(cue));
}

function hasCareerBehaviorDetail(normalized: string): boolean {
  return [
    "requested an interview",
    "got an interview",
    "have an interview",
    "landed an interview",
    "slid into my dms",
    "reached out",
    "applied",
    "sending cold dms",
    "send cold dms",
    "cold dms",
    "job hunt",
    "job search",
    "internship hunt",
    "application",
    "offer",
  ].some((cue) => normalized.includes(cue));
}

function hasCareerStakeDetail(normalized: string): boolean {
  return [
    "requested an interview",
    "got an interview",
    "have an interview",
    "deadline",
    "need to",
    "trying to",
    "want to land",
    "want an internship",
    "internship hunt",
    "job hunt",
    "job search",
    "offer",
    "recruiter",
    "application",
    "resume",
  ].some((cue) => normalized.includes(cue));
}

function inferAmbiguousReference(args: {
  normalizedMessage: string;
  contextAnchors: string[];
}): { needsClarification: boolean; reference: string | null } {
  const { normalizedMessage } = args;

  const hasAmpmToken = /\bampm\b/i.test(normalizedMessage) || /\bam\/pm\b/i.test(normalizedMessage);
  if (!hasAmpmToken) {
    return {
      needsClarification: false,
      reference: null,
    };
  }

  const messageHasAmpmDisambiguationCue = [
    "club",
    "downtown",
    "toronto",
    "convenience store",
    "gas station",
    "time of day",
    "time-of-day",
    "morning",
    "night",
    "am/pm",
  ].some((cue) => normalizedMessage.includes(cue));

  const anchorsJoined = args.contextAnchors.join(" ").toLowerCase();
  const anchorDisambiguatesAmpm =
    /\bampm\b/.test(anchorsJoined) &&
    [
      "club",
      "downtown",
      "toronto",
      "convenience store",
      "gas station",
      "time of day",
      "time-of-day",
      "morning",
      "night",
      "am/pm",
    ].some((cue) => anchorsJoined.includes(cue));

  return {
    needsClarification: !messageHasAmpmDisambiguationCue && !anchorDisambiguatesAmpm,
    reference: "ampm",
  };
}

export function evaluateDraftContextSlots(args: {
  userMessage: string;
  topicSummary: string | null;
  contextAnchors: string[];
}): DraftContextSlots {
  const trimmed = args.userMessage.trim();
  const normalized = trimmed.toLowerCase();
  const namedEntity = inferNamedEntity(trimmed);
  const productCuePresent = ["tool", "app", "product", "extension", "plugin"].some((cue) =>
    normalized.includes(cue),
  );
  const ambiguousReference = inferAmbiguousReference({
    normalizedMessage: normalized,
    contextAnchors: args.contextAnchors,
  });
  const careerCuePresent = hasCareerCue(normalized);
  const looksLikeComparison = Boolean(inferComparisonReference(trimmed));
  const isProductLike =
    looksLikeBuildMessage(normalized) ||
    productCuePresent ||
    Boolean(inferBuildSubject(trimmed)) ||
    (Boolean(namedEntity) && looksLikeComparison) ||
    (Boolean(namedEntity) && hasRelationshipDetail(normalized));
  const subjectKnown = Boolean((args.topicSummary || trimmed).trim());
  const localContext = `${normalized} ${(args.topicSummary || "").toLowerCase()}`.trim();
  const externalContextKnown =
    !namedEntity ||
    localContext.includes(`${namedEntity.toLowerCase()} is`) ||
    localContext.includes(`${namedEntity.toLowerCase()}:`) ||
    (localContext.includes(namedEntity.toLowerCase()) && hasFunctionalDetail(localContext));
  const entityNeedsDefinition =
    isProductLike && Boolean(namedEntity) && !externalContextKnown;
  const domainHint: DraftContextDomainHint = isProductLike
    ? "product"
    : careerCuePresent
      ? "career"
      : subjectKnown
        ? "creator"
        : "general";

  const behaviorKnown =
    domainHint === "career"
      ? hasCareerBehaviorDetail(normalized)
      : hasFunctionalDetail(normalized);
  const stakesKnown =
    domainHint === "career"
      ? hasCareerStakeDetail(normalized)
      : hasProblemDetail(normalized);

  return {
    subjectKnown,
    behaviorKnown,
    stakesKnown,
    externalContextKnown,
    entityNeedsDefinition,
    namedEntity,
    ambiguousReferenceNeedsClarification: ambiguousReference.needsClarification,
    ambiguousReference: ambiguousReference.reference,
    isProductLike,
    domainHint,
  };
}
