import { fetchJsonFromGroq } from "./llm";
import { z } from "zod";

export const IntentClassificationSchema = z.object({
  intent: z.enum(["coach", "ideate", "draft", "review", "edit", "answer_question"]),
  needs_memory_update: z.boolean(),
  confidence: z.number().min(0).max(1),
});

export type IntentClassification = z.infer<typeof IntentClassificationSchema>;

/**
 * High speed, deterministic intent classifier using openai/gpt-oss-120b.
 * Decides what mode the orchestrator should run next.
 * 
 * CONSERVATIVE BIAS: When in doubt, route to "coach" so the agent asks a question
 * rather than generating content the user didn't explicitly ask for.
 */
export async function classifyIntent(
  userMessage: string,
  recentHistory: string,
): Promise<IntentClassification | null> {
  const instruction = `
You are an intent classifier for a creator growth chatbot.
Your job: classify what the user wants to do based on their message AND the recent conversation context.

INTENTS (read carefully before deciding):
- "draft": 
  1. User explicitly says write/draft/generate a post AND provides a clear topic.
  2. User says "write me another post", "write something", "just write anything", "generate another one" — they want content NOW, not more questions.
  3. User is quoting an ideation question AND provides a clear answer along with it.
  4. User has ALREADY provided a topic/angle earlier in the conversation and now says something like "ok write it" or "go ahead" or even just provides a short answer to a probing question — they want a draft.
  NOT: Sending ONLY a quoted question with no actual answer — route to "coach".
  
- "ideate": User asks for post ideas, angles, or inspiration.
  e.g. "give me some ideas", "what should I write about today?", "help me draft some post ideas"
  NOT: "write this post for me" (that is draft)
  NOT: "> What unexpected win..." (quoting an idea = draft)
  
- "edit": User is modifying a draft that was just generated by you.
  e.g. "make it shorter", "remove the emojis", "rewrite the first line", "i don't like this part"

- "answer_question": User asks a direct factual question about their strategy, X algorithm, niche, or about themselves.
  e.g. "what do you know about me?", "summarize me", "what are my preferences?"

- "coach": DEFAULT when message is truly vague with NO topic context from the conversation.
  Examples: "help me grow", "hello", a quoted question with no answer.
  IMPORTANT: Do NOT route to coach if the user has already given you a topic and is now saying "just write it" or providing a brief answer. That's a DRAFT.

GOLDEN RULE: Look at the FULL conversation. If the user has ALREADY discussed a topic and now wants content, route to "draft". Only route to "coach" if you genuinely need more info to proceed.

Respond ONLY with valid JSON:
{
  "intent": "coach" | "ideate" | "draft" | "review" | "edit" | "answer_question",
  "needs_memory_update": boolean,
  "confidence": number // 0.0 to 1.0
}
  `.trim();

  const data = await fetchJsonFromGroq<unknown>({
    model: process.env.GROQ_MODEL || "openai/gpt-oss-120b",
    reasoning_effort: "low",
    temperature: 0.1,
    top_p: 0.9,
    max_tokens: 256,
    messages: [
      { role: "system", content: instruction },
      { role: "user", content: `Recent History:\n${recentHistory}\n\nUser Message:\n${userMessage}` },
    ],
  });

  if (!data) return null;

  try {
    return IntentClassificationSchema.parse(data);
  } catch (err) {
    console.error("Classifier validation failed", err);
    return null;
  }
}
