import { fetchJsonFromGroq } from "./llm";
import { z } from "zod";

export const IntentClassificationSchema = z.object({
  intent: z.enum(["coach", "ideate", "draft", "review", "edit", "answer_question"]),
  needs_memory_update: z.boolean(),
  confidence: z.number().min(0).max(1),
});

export type IntentClassification = z.infer<typeof IntentClassificationSchema>;

/**
 * High speed, deterministic intent classifier using openai/gpt-oss-120b.
 * Decides what mode the orchestrator should run next.
 * 
 * CONSERVATIVE BIAS: When in doubt, route to "coach" so the agent asks a question
 * rather than generating content the user didn't explicitly ask for.
 */
export async function classifyIntent(
  userMessage: string,
  recentHistory: string,
): Promise<IntentClassification | null> {
  const instruction = `
You are an intent classifier for a creator growth chatbot.
Your job: classify what the user wants to do, conservatively.

INTENTS (read carefully before deciding):
- "draft": ONLY if user explicitly says write/draft/generate a specific post AND provides a clear topic. 
  e.g. "write a post about how I fixed my DB migration bug"
  NOT: "write a post in my voice", "help me draft something", "I want to post"
  
- "ideate": ONLY if user has already told you a SPECIFIC topic and wants angles/options.
  e.g. "give me angles on the API auth bug I fixed" (topic = API auth bug)
  NOT: "help me figure out what to post" (no specific topic yet)
  NOT: "building a project" (too vague, no real angle yet)
  
- "edit": User is modifying a draft that was just generated by you.

- "answer_question": User asks a direct factual question about their strategy, X algorithm, niche.

- "coach": **DEFAULT for everything else.** When message is vague, topicless, or unclear — always route here.
  Examples of coach:
  - "write a post in my voice" (no topic specified)
  - "help me grow"
  - "I want to post something"
  - "building a project" (no specific post angle)
  - "I don't know what to post"
  - Any message where you'd need to ask "what do you want to post about?" first

GOLDEN RULE: If a post could not be written without asking the user for more info, classify as "coach".

Respond ONLY with valid JSON:
{
  "intent": "coach" | "ideate" | "draft" | "review" | "edit" | "answer_question",
  "needs_memory_update": boolean,
  "confidence": number // 0.0 to 1.0
}
  `.trim();

  const data = await fetchJsonFromGroq<unknown>({
    model: process.env.GROQ_MODEL || "openai/gpt-oss-120b",
    reasoning_effort: "low",
    temperature: 0.1,
    top_p: 0.9,
    max_tokens: 256,
    messages: [
      { role: "system", content: instruction },
      { role: "user", content: `Recent History:\n${recentHistory}\n\nUser Message:\n${userMessage}` },
    ],
  });

  if (!data) return null;

  try {
    return IntentClassificationSchema.parse(data);
  } catch (err) {
    console.error("Classifier validation failed", err);
    return null;
  }
}
