export const LIVE_ASSISTANT_EVAL_FIXTURES = [
  {
    category: "continuity",
    name: "stored active draft stays in scope for short follow-up edits",
    activeDraftRef: {
      messageId: "assistant_msg_1",
      versionId: "draft_v2",
    },
    history: [
      {
        id: "assistant_msg_1",
        role: "assistant",
        content: "here's the latest version",
        data: {
          assistant_context_v2: {
            contextPacket: {
              draftRef: {
                activeDraftVersionId: "draft_v2",
                excerpt: "xpo helps turn rough ideas into posts you can actually ship.",
                revisionChainId: "chain_1",
              },
            },
          },
          draftVersions: [
            {
              id: "draft_v1",
              content: "old draft",
            },
            {
              id: "draft_v2",
              content: "xpo helps turn rough ideas into posts you can actually ship.",
            },
          ],
        },
      },
      {
        role: "user",
        content: "make that punchier",
      },
    ],
    followUpMessage: "make that punchier",
    controllerMemory: {
      conversationState: "drafting",
      topicSummary: "xpo launch",
      hasPendingPlan: false,
      hasActiveDraft: true,
      unresolvedQuestion: null,
      concreteAnswerCount: 1,
      pendingPlanSummary: null,
      latestRefinementInstruction: null,
      lastIdeationAngles: [],
    },
    expectedActiveDraft: "xpo helps turn rough ideas into posts you can actually ship.",
    expectedAction: "revise",
  },
  {
    category: "controller",
    name: "direct comparison questions are not hijacked by artifact heuristics",
    userMessage: "what changed between option 1 and option 2?",
    controllerMemory: {
      conversationState: "ready_to_ideate",
      topicSummary: "xpo positioning",
      hasPendingPlan: false,
      hasActiveDraft: false,
      unresolvedQuestion: null,
      concreteAnswerCount: 0,
      pendingPlanSummary: null,
      latestRefinementInstruction: null,
      lastIdeationAngles: [
        "why context loss makes ai feel generic",
        "why brittle routing kills continuity",
      ],
    },
    expectedAction: null,
  },
  {
    category: "memory_scope",
    name: "topic switch after active draft clears draft-scoped residue but keeps durable constraints",
    userMessage: "switch gears and help me write about hiring mistakes instead",
    memory: {
      conversationState: "draft_ready",
      activeConstraints: [
        "Correction lock: handle a is not the 30M ARR company.",
        "keep all lowercase",
      ],
      topicSummary: "xpo launch thread",
      lastIdeationAngles: ["ship the ugly first version"],
      concreteAnswerCount: 3,
      currentDraftArtifactId: "draft_123",
      activeDraftRef: {
        messageId: "assistant_msg_1",
        versionId: "draft_v2",
      },
      rollingSummary: "Current topic: xpo launch",
      pendingPlan: {
        objective: "xpo launch thread",
        angle: "show why ugly launches compound faster than polished waiting",
        targetLane: "original",
        mustInclude: [],
        mustAvoid: [],
        hookType: "direct",
        pitchResponse: "lead with the ugly first version",
      },
      clarificationState: null,
      assistantTurnCount: 4,
      latestRefinementInstruction: "make it punchier",
      unresolvedQuestion: "do you want this as a thread or a single post?",
      clarificationQuestionsAsked: 1,
      preferredSurfaceMode: "natural",
      formatPreference: "thread",
      activeReplyContext: null,
      activeReplyArtifactRef: null,
      selectedReplyOptionId: null,
      voiceFidelity: "balanced",
    },
    expectedConversationState: "ready_to_ideate",
    expectedTopicSummary: null,
    expectedCurrentDraftArtifactId: null,
    expectedActiveConstraints: [
      "Correction lock: handle a is not the 30M ARR company.",
      "keep all lowercase",
    ],
  },
  {
    category: "memory_scope",
    name: "topic switch after active reply context clears reply residue before the new topic",
    userMessage: "different topic: write a post about onboarding mistakes",
    memory: {
      conversationState: "draft_ready",
      activeConstraints: ["keep all lowercase"],
      topicSummary: "reply strategy",
      lastIdeationAngles: [],
      concreteAnswerCount: 1,
      currentDraftArtifactId: null,
      activeDraftRef: null,
      rollingSummary: "Current topic: reply strategy",
      pendingPlan: null,
      clarificationState: null,
      assistantTurnCount: 2,
      latestRefinementInstruction: null,
      unresolvedQuestion: null,
      clarificationQuestionsAsked: 0,
      preferredSurfaceMode: "structured",
      formatPreference: "shortform",
      activeReplyContext: {
        sourceText: "Most people optimize for approval first.",
        sourceUrl: "https://x.com/creator/status/1",
        authorHandle: "creator",
        quotedUserAsk: "how should i reply to that?",
        confidence: "high",
        parseReason: "reply_ask_with_post_metadata",
        awaitingConfirmation: false,
        stage: "0_to_1k",
        tone: "builder",
        goal: "followers",
        opportunityId: "chat-reply-1",
        latestReplyOptions: [{ id: "opt-1", label: "nuance", text: "Option 1" }],
        latestReplyDraftOptions: [],
        selectedReplyOptionId: "opt-1",
      },
      activeReplyArtifactRef: {
        messageId: "assistant_reply_1",
        kind: "reply_options",
      },
      selectedReplyOptionId: "opt-1",
      voiceFidelity: "balanced",
    },
    expectedConversationState: "ready_to_ideate",
    expectedTopicSummary: null,
    expectedCurrentDraftArtifactId: null,
    expectedActiveConstraints: ["keep all lowercase"],
    expectedReplyCleared: true,
  },
  {
    category: "grounding",
    name: "first-pass drafts reject invented product usage and mechanics",
    activeConstraints: [
      "Topic grounding: Xpo helps users repurpose existing ideas into X posts and replies.",
    ],
    sourceUserMessage: "write a post about xpo",
    draft:
      "i built xpo to scan engagement timing, handle the rest, and remove the mental load from posting.",
    expectedReasonPattern: /invented first-person product usage|adjacent product mechanics/i,
  },
  {
    category: "revision",
    name: "expansion and specificity edits stay local and grounded",
    activeDraft: "xpo helps turn rough ideas into posts you can actually ship.",
    expansionMessage: "make it longer and more detailed",
    specificityMessage: "make it more specific",
  },
] as const;
