export const CONTROLLER_WORKFLOW_EVAL_FIXTURES = [
  {
    category: "controller_workflow",
    name: "direct answers stay in answer_question workflow",
    action: "answer",
    memory: {
      conversationState: "answering",
      topicSummary: "xpo positioning",
      hasPendingPlan: false,
      hasActiveDraft: false,
      unresolvedQuestion: null,
      concreteAnswerCount: 1,
    },
    expectedIntent: "answer_question",
  },
  {
    category: "controller_workflow",
    name: "retrieve_then_answer still resolves through answer_question workflow",
    action: "retrieve_then_answer",
    memory: {
      conversationState: "answering",
      topicSummary: "best posts",
      hasPendingPlan: false,
      hasActiveDraft: false,
      unresolvedQuestion: null,
      concreteAnswerCount: 2,
    },
    expectedIntent: "answer_question",
  },
  {
    category: "controller_workflow",
    name: "ask actions stay in coach workflow when facts are missing",
    action: "ask",
    memory: {
      conversationState: "answering",
      topicSummary: "xpo product story",
      hasPendingPlan: false,
      hasActiveDraft: false,
      unresolvedQuestion: "What is true about the product that can be claimed publicly?",
      concreteAnswerCount: 0,
    },
    expectedIntent: "coach",
  },
] as const;

export const REPLY_WORKFLOW_EVAL_FIXTURES = [
  {
    category: "reply_workflow",
    name: "reply options stay grounded and distinct for niche-relevant opportunities",
    kind: "options",
    payload: {
      post: {
        postId: "post_1",
        author: {
          id: "author_1",
          handle: "builder",
          name: "Builder",
          verified: false,
          followerCount: 6200,
        },
        text: "Most people talk about positioning like a slogan problem instead of a product problem.",
        url: "https://x.com/builder/status/1",
        createdAtIso: "2026-03-11T10:00:00.000Z",
        engagement: {
          replyCount: 3,
          repostCount: 1,
          likeCount: 12,
          quoteCount: 0,
          viewCount: 550,
        },
        postType: "original",
        conversation: {
          conversationId: "conv_1",
          inReplyToPostId: null,
          inReplyToHandle: null,
        },
        media: {
          hasMedia: false,
          hasImage: false,
          hasVideo: false,
          hasGif: false,
          hasLink: false,
          hasPoll: false,
        },
        surface: "home",
        captureSource: "graphql",
        capturedAtIso: "2026-03-11T10:10:00.000Z",
      },
      opportunity: {
        opportunityId: "opp_1",
        postId: "post_1",
        score: 79,
        verdict: "reply",
        why: ["Strong niche overlap with your saved content pillars."],
        riskFlags: [],
        suggestedAngle: "nuance",
        expectedValue: {
          visibility: "high",
          profileClicks: "high",
          followConversion: "medium",
        },
        scoringBreakdown: {
          niche_match: 82,
          audience_fit: 74,
          freshness: 88,
          conversation_quality: 79,
          profile_click_potential: 84,
          follow_conversion_potential: 72,
          visibility_potential: 70,
          spam_risk: 8,
          off_niche_risk: 12,
          genericity_risk: 18,
          negative_signal_risk: 5,
        },
      },
      strategy: {
        knownFor: "software and product through product positioning",
        targetAudience: "builders who want clearer positioning on X",
        contentPillars: ["product positioning", "reply leverage", "proof-first posting"],
        replyGoals: ["Turn relevant replies into profile clicks from the right niche."],
        profileConversionCues: ["Bio and pinned post should make the niche obvious."],
        offBrandThemes: ["broad motivational advice with no niche tie"],
        ambiguities: [],
        confidence: {
          overall: 72,
          positioning: 70,
          replySignal: 64,
          readiness: "ready",
        },
        truthBoundary: {
          verifiedFacts: ["Primary niche: software and product"],
          inferredThemes: ["product positioning", "reply leverage"],
          unknowns: [],
        },
      },
      strategyPillar: "product positioning",
      styleCard: null,
      stage: "0-1k",
      tone: "builder",
      goal: "followers",
    },
  },
  {
    category: "reply_workflow",
    name: "reply drafts avoid invented first-person and numeric claims",
    kind: "draft",
    payload: {
      request: {
        tweetId: "tweet_2",
        tweetText: "How do you make replies worth reading instead of generic agreement?",
        authorHandle: "creator",
        tweetUrl: "https://x.com/creator/status/2",
        stage: "0_to_1k",
        tone: "dry",
        goal: "followers",
      },
      strategy: {
        knownFor: "software and product through product positioning",
        targetAudience: "builders who want clearer positioning on X",
        contentPillars: ["product positioning", "reply leverage", "proof-first posting"],
        replyGoals: ["Turn relevant replies into profile clicks from the right niche."],
        profileConversionCues: ["Bio and pinned post should make the niche obvious."],
        offBrandThemes: ["broad motivational advice with no niche tie"],
        ambiguities: [
          "The account still reads broad, so default to software and product until stronger proof arrives.",
        ],
        confidence: {
          overall: 68,
          positioning: 63,
          replySignal: 51,
          readiness: "caution",
        },
        truthBoundary: {
          verifiedFacts: ["Primary niche: software and product"],
          inferredThemes: ["product positioning", "reply leverage"],
          unknowns: ["No profile click data yet."],
        },
      },
    },
  },
] as const;
